CREATE TABLE containers (
    id SERIAL PRIMARY KEY,
    container_id VARCHAR(255) NOT NULL UNIQUE,
    container_name VARCHAR(255) NOT NULL UNIQUE,
    image_name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
